import pygame
import sys
import time

# Initialize pygame
pygame.init()

# Set up display
board_size = 8
square_size = 80  # Size of each square
width = board_size * square_size
height = board_size * square_size
screen = pygame.display.set_mode((width, height))
pygame.display.set_caption('Solving the Knight/’s Tour problem using a genetic algorithm ')

# Colors
white = (255, 255, 255)
black = (0, 0, 0)
green = (0, 255, 0)
blue = (0, 0, 255)

# Load knight image or create a simple circle representation
knight_color = (0, 0, 255)

def draw_board():
    for row in range(board_size):
        for col in range(board_size):
            color = white if (row + col) % 2 == 0 else black
            pygame.draw.rect(screen, color, (col * square_size, row * square_size, square_size, square_size))
 
knight_image = pygame.image.load('chess.png')
knight_image = pygame.transform.scale(knight_image, (square_size, square_size))

def draw_knight(position):
    row, col = position
    screen.blit(knight_image, (col * square_size, row * square_size))

def animate_knight_tour(movs):
    for position in movs:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
        
        draw_board()
        draw_knight(position)
        pygame.display.flip()
        time.sleep(0.5) 

# Example path for demonstration (replace this with the path generated by your genetic algorithm)
example_path = [(0, 0), (2, 1), (4, 2), (6, 3), (7, 5), (5, 6), (3, 7), (1, 6)]

# Main loop
animate_knight_tour(example_path)

# Wait before closing
time.sleep(2)
pygame.quit()
